### ISSUE TITLE
RuntimeError: Function MmBackward returned an invalid gradient at index 0

### ISSUE THREAD

**Issue by huanggewudi** [Jthy-af/HaPPy#2]
(pyg) ubuntu@ubuntu:/mnt/disk/hzy/pyg/HaPPy$ python train.py 
loading data
start training
epoch: 0  i 0  loss: 48.30012893676758
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    my_train(train_loader, val_loader, test_set, metadata, filepath)
  File "train.py", line 214, in my_train
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function MmBackward returned an invalid gradient at index 0 - got [404292, 74] but expected shape compatible with [404292, 76]

这个是怎么回事啊

**Comment by huanggewudi** [comment]
self.ligandgnn = AttentiveFP(in_channels=18, hidden_channels=64, out_channels=16, edge_dim=10, num_timesteps=3,
                                     num_layers=3)
                                     
                                     
                                     edge_dim 改为 12

**Comment by huanggewudi** [comment]
self.proteingnn = AttentiveFP(in_channels=18,hidden_channels=64,out_channels=16,edge_dim=10,num_timesteps=3,num_layers=3)

edge_dim该为12

**Comment by Jthy-af** [comment]
[404292, 74] --[404292, 76]，应该是embedding向量的维度没对上，检查下预处理原数据时候，构建出图的维度和后面GNN的维度，你修改edge_dim是对的。应该是当时做消融实验一直改参数，最后打包代码的时候没核对好。这些其实都是可以调整的超参数，只要将构建图和GNN的对应参数对齐就好。

**Comment by Jthy-af** [comment]
> self.proteingnn = AttentiveFP(in_channels=18,hidden_channels=64,out_channels=16,edge_dim=10,num_timesteps=3,num_layers=3)
> 
> edge_dim该为12

[404292, 74] --[404292, 76]，应该是embedding向量的维度没对上，检查下预处理原数据时候，构建出图的维度和后面GNN的维度，你修改edge_dim是对的。应该是当时做消融实验一直改参数，最后打包代码的时候没核对好。这些其实都是可以调整的超参数，只要将构建图和GNN的对应参数对齐就好。

**Comment by CraboyFan** [comment]
大佬，训练完一个epoch脚本里会用my_test这个函数进行测试的时候有遇到这个问题吗
当前环境torch_geometric的版本是2.4.0，torch版本是2.1.2
问题如下
(Latest_01) zd@Z2://nas2_public/zhida_data/workdir/HaPPy$ python train.py 
loading data
start training
epoch: 0  i 0  loss: 48.64824295043945
epoch: 0  i 1  loss: 47.402076721191406
epoch: 0  i 2  loss: 50.3048095703125
epoch: 0  i 3  loss: 47.99046325683594
epoch: 0  i 4  loss: 47.509281158447266
epoch: 0  i 5  loss: 48.02720642089844
epoch: 0  i 6  loss: 46.11945343017578
epoch: 0  i 7  loss: 48.41754913330078
epoch: 0  i 8  loss: 46.40046691894531
epoch: 0  i 9  loss: 46.43372344970703
epoch: 0  i 10  loss: 47.274513244628906
epoch: 0  i 11  loss: 45.469120025634766
epoch: 0  i 12  loss: 45.764610290527344
epoch: 0  i 13  loss: 45.00320816040039
epoch: 0  i 14  loss: 44.99822235107422
epoch: 0  i 15  loss: 46.94007110595703
epoch: 0  i 16  loss: 47.65935516357422
epoch: 0  i 17  loss: 45.82853698730469
epoch: 0  i 18  loss: 45.79132080078125
epoch: 0  i 19  loss: 44.791748046875
epoch: 0  i 20  loss: 45.79370880126953
epoch: 0  i 21  loss: 44.475006103515625
epoch: 0  i 22  loss: 43.39085388183594
epoch: 0  i 23  loss: 43.8657112121582
epoch: 0  loss: 46.42913579940796
********save model*********
epoch: 0 mae: 6.47214739293375 rmse: 6.700850671294984
Traceback (most recent call last):
  File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 317, in <module>
    my_train(train_loader, val_loader, test_set, metadata, filepath)
  File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 231, in my_train
    test_mae, test_rmse = my_test(test_set, metadata, kf_filepath+'best_model.pt')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 253, in my_test
    best_model.load_state_dict(m_state_dict)
  File "/nas2_public/soft/Miniforge-pypy3-23.11.0-0/envs/Latest_01/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BIPLnet:
        While copying the parameter named "heterognn.conv_1.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_1.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_1.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_1.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_2.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_2.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_2.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_2.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_3.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_3.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_3.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
        While copying the parameter named "heterognn.conv_3.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).

> self.proteingnn = AttentiveFP(in_channels=18,hidden_channels=64,out_channels=16,edge_dim=10,num_timesteps=3,num_layers=3)
> 
> edge_dim该为12

**Comment by Jthy-af** [comment]
> 大佬，训练完一个epoch脚本里会用my_test这个函数进行测试的时候有遇到这个问题吗 当前环境torch_geometric的版本是2.4.0，torch版本是2.1.2 问题如下 (Latest_01) zd@Z2://nas2_public/zhida_data/workdir/HaPPy$ python train.py loading data start training epoch: 0 i 0 loss: 48.64824295043945 epoch: 0 i 1 loss: 47.402076721191406 epoch: 0 i 2 loss: 50.3048095703125 epoch: 0 i 3 loss: 47.99046325683594 epoch: 0 i 4 loss: 47.509281158447266 epoch: 0 i 5 loss: 48.02720642089844 epoch: 0 i 6 loss: 46.11945343017578 epoch: 0 i 7 loss: 48.41754913330078 epoch: 0 i 8 loss: 46.40046691894531 epoch: 0 i 9 loss: 46.43372344970703 epoch: 0 i 10 loss: 47.274513244628906 epoch: 0 i 11 loss: 45.469120025634766 epoch: 0 i 12 loss: 45.764610290527344 epoch: 0 i 13 loss: 45.00320816040039 epoch: 0 i 14 loss: 44.99822235107422 epoch: 0 i 15 loss: 46.94007110595703 epoch: 0 i 16 loss: 47.65935516357422 epoch: 0 i 17 loss: 45.82853698730469 epoch: 0 i 18 loss: 45.79132080078125 epoch: 0 i 19 loss: 44.791748046875 epoch: 0 i 20 loss: 45.79370880126953 epoch: 0 i 21 loss: 44.475006103515625 epoch: 0 i 22 loss: 43.39085388183594 epoch: 0 i 23 loss: 43.8657112121582 epoch: 0 loss: 46.42913579940796 **save model*** epoch: 0 mae: 6.47214739293375 rmse: 6.700850671294984 Traceback (most recent call last): File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 317, in my_train(train_loader, val_loader, test_set, metadata, filepath) File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 231, in my_train test_mae, test_rmse = my_test(test_set, metadata, kf_filepath+'best_model.pt') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/nas2_public/zhida_data/workdir/HaPPy/train.py", line 253, in my_test best_model.load_state_dict(m_state_dict) File "/nas2_public/soft/Miniforge-pypy3-23.11.0-0/envs/Latest_01/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for BIPLnet: While copying the parameter named "heterognn.conv_1.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_1.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_1.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_1.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 18]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (18) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_2.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_2.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_2.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_2.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_3.convs.<ligand___to___protein>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_3.convs.<ligand___to___protein>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_3.convs.<protein___rev_to___ligand>.lin_l.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',). While copying the parameter named "heterognn.conv_3.convs.<protein___rev_to___ligand>.lin_r.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([64, 64]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (64) at non-singleton dimension 1',).
> 
> > self.proteingnn = AttentiveFP(in_channels=18,hidden_channels=64,out_channels=16,edge_dim=10,num_timesteps=3,num_layers=3)
> > edge_dim该为12

我之前没有见过这个错误，它看起来是保存的模型参数无法在测试的时候正确加载，我建议你使用和开源的yaml文件中一致的pyg版本。然后我刚看到这里https://github.com/pyg-team/pytorch_geometric/discussions/8422
对这个问题做了一些讨论，或许对你有帮助。大概率应该就是pyg版本的问题。

**Comment by CraboyFan** [comment]
嗯嗯，感谢佬的回答，但是再配置一个虚拟环境实在有点耗时。上面报错显示checkpoint中的对应参数尺寸是 (64, 18) 或者 (64, 64)，但在模型的在设计时参数尺寸是 (0)，我看了下train.py出现错误的这三层是这样的：
self.conv_1 = HeteroConv(
            {
                edge_type: SAGEConv([-1,-1],hidden_channels)
                            for edge_type in metadata[1]
            }
        )
        self.conv_2 = HeteroConv(
            {
                edge_type: SAGEConv([-1,-1],hidden_channels)
                            for edge_type in metadata[1]
            }
        )
        self.conv_3 = HeteroConv(
            {
                edge_type: SAGEConv([-1,-1],hidden_channels)
                            for edge_type in metadata[1]
            }
        )
        我直接按照checkpoint中的参数尺寸固定了，然后这样也行，其中缘由我不是太懂，学的太浅了[惭愧]
